### ISSUE TITLE
Calculating Incoming solar radiation - Error in function ?

### ISSUE THREAD

**Issue by raoulcollenteur** [phydrus/pyet#15]
### Discussed in https://github.com/phydrus/pyet/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **manlaya** September 15, 2021</sup>
Hello everyone,

I was trying to compute ET with this module and synop data in France and comparing methods (*Turc, Hargreaves, Penman-Monteith, FAO56*).
When computing Incoming solar radiation with ```calc_rad_sol_in()``` I had some differences with the code I used before to do such calculations.

Looking at the code, I saw that the equation used is : 
``` (as1 + bs1 * n / nn) * ra ``` 
- with ```n``` as duration of sunshine ;
- and ```nn``` as maximum possible duration of sunshine

In this ```calc_rad_sol_in()``` function, ```n``` is optionnal and calculate with ```daylight_hours()``` when ```None```, using day_of_the_year, sunset_angle, etc.

Actually, aren't ```n``` and ```nn``` variables inverted here ? 

I mean, not in ```n/nn``` term but what is compute by ```daylight_hours()``` should be ```nn``` variable to correspond to eq 34 and 35 given by Allen *et al.* (1998). ```n``` should then be sunshine duration measured.

Not quite sure if it's an issue or if I am missing something in my use of this module, so I am posting this question here...

Thanks in advance for your answers.

Kind regards,
Adrien</div>

**Comment by mvremec** [comment]
Please check: `https://github.com/phydrus/pyet/discussions/13`
