### ISSUE TITLE
[BUG] daylight_hours return nans for high latitudes

### ISSUE THREAD

**Issue by raoulcollenteur** [phydrus/pyet#25]
pyet.daylight_hours returns NaNs for high latitudes (e.g., Sweden) in winter, this should returns zero (hours of daylight) I think.

To reproduce:

`pyet.daylight_hours(df.index, 70*(np.pi/180)). # where df.index is somewhere in January`

**Comment by mvremec** [comment]
Hei Raoul,
Thank you for this! This should be fixed in the pyet_xarray branch. Let's try to push to main this week.
