### ISSUE TITLE
fix ReadTheDocs issues

### ISSUE THREAD

**Issue by raoulcollenteur** [phydrus/pyet#33]
Some things need to be improved in the Docs:

- [x] PDFlatex cannot be built, simply do not built it.
- [x] Some methods are not in the API docs, see e.g., Haude
- [x] Add Github link to Docs right-top corner
- [ ] .. something else?

**Comment by raoulcollenteur** [comment]
I find the "Methods" section unnecessary, since the formulas are also in the docstrings. This is simply a lot of work to maintain and check, since it needs to be checked in two places now. Can we not remove this part and state clearly that the formulas are in the docstrings/apidocs?

**Comment by mvremec** [comment]
This is true! You can delete the "Methods" section.

**Comment by raoulcollenteur** [comment]
Done with everything, closing issue.
