### ISSUE TITLE
To do list:

### ISSUE THREAD

**Issue by mvremec** [phydrus/PyEt#4]
Add additional methods:

- [ ] add Thornthwaite method
- [ ] add ASCE_2000 method

Extend to  enable 2D and  data input:

- [ ]  Numpy Arrays
- [ ] XArray
- [ ] NetCDF

Extend to enable different temporal resolution:

- [ ] hourly
- [ ] monthly
- [ ] yearly
- [ ] half-hourly,15min, 10min

**Comment by raoulcollenteur** [comment]
This should not be an issue, but a project ;-) Move it there and close this Issue.

**Comment by mvremec** [comment]
Hi @dgketchum, 
Thank you for your response! The extension to operate on 2D is already available on the [pyet_xarray](https://github.com/phydrus/pyet/tree/pyet_xarray) branch. It is compatible with xarray.DataArray for now. I added an example where we import netcdf4 files with xarray and then estimate ET in 2D. You can find an example [here](https://github.com/phydrus/pyet/blob/pyet_xarray/examples/02_example_zamg_netcdf.ipynb).
I haven't merged it with the main repo yet as I wanted to include some more examples.
Let me know if it works for you.

**Comment by dgketchum** [comment]
Awesome, thanks so much! I should have checked your branches. I'll let you know if I come across anything that needs your attention, or help. This software is going to save me a lot of time! Cheers,
