### ISSUE TITLE
Pypi not updating with GitHub Actions

### ISSUE THREAD

**Issue by OuyangWenyu** [phydrus/pyet#7]
## What happened

After I used pip to install pyet, I  tried to run the example in https://github.com/phydrus/pyet/blob/master/examples/02_example_coagmet.ipynb

However, I got an unexpected result:

![image](https://user-images.githubusercontent.com/10172837/118073189-ee2cf480-b3dd-11eb-8e7c-c8fae89f48ec.png)

But when I downloaded the pyet manually, put them in my directory (I put them in a directory named "src", and import src.pyet as pyet), and run the same code. It worked.

![image](https://user-images.githubusercontent.com/10172837/118073290-20d6ed00-b3de-11eb-8404-5bed7a088248.png)

I am not sure if it only happened in my own environment.

## My python environment:

```conda
matplotlib                3.3.2                         0    conda-forge
numpy                     1.20.1           py37h93e21f0_0  
pandas                    1.2.4            py37h2531618_0  
python                    3.7.9           hffdb5ce_0_cpython    conda-forge
```

**Comment by raoulcollenteur** [comment]
Hi @OuyangWenyu! Thanks for the bug report, indeed the master branch does not match Pypi.

@mvremec , can you make a new Github Release that will trigger the Action and update Pypi?

**Comment by OuyangWenyu** [comment]
Thanks! I look forward to the new version.

**Comment by raoulcollenteur** [comment]
@mvremec . Maybe do a manual release to Pypi of v0.2. Then we figure out what is wrong with the @GitHub Actions not working later.

**Comment by mvremec** [comment]
Hi @OuyangWenyu and thank you for this! 

We have some troubles with @github Actions not updating Pypi. 
Version 1.0 of pyet should now be available through Pypi.
Using version 1.0, the above issue should be solved.

You can run `pip install --upgrade pyet` to upgrade to version 1.0!

Have fun using pyet!

**Comment by OuyangWenyu** [comment]
Thanks!
